//! # Private Cross-Chain RFQ Desk — Program Entrypoint
//!
//! This is the main entrypoint and instruction dispatcher for the `private_rfq`
//! Solana program. Built on **Pinocchio** for compatibility with both the
//! Encrypt (FHE) and Ika (dWallet) pre-alpha SDKs, which cannot share a common
//! Anchor framework version.
//!
//! ## Instruction Dispatch Table
//!
//! | Discriminator | Instruction              | Purpose                                  |
//! |:---:|:---|:---|
//! | `0`           | `initialize_rfq`         | Maker opens an encrypted RFQ             |
//! | `1`           | `submit_bid`             | Taker submits bid + locks USDC escrow    |
//! | `2`           | `request_fhe_match`      | CPI to Encrypt `execute_graph`           |
//! | `3`           | `request_match_decrypt`  | CPI to Encrypt `request_decryption`      |
//! | `4`           | `reveal_match`           | Read decryption result; settle or refund |
//! | `5`           | `execute_settlement`     | CPI to Ika `approve_message`             |
//! | `6`           | `force_cancel_timeout`   | Emergency reset after 200-block stall    |
//!
//! ## Zero-Trust Architecture
//!
//! This program never stores or can decrypt plaintext trade parameters.
//! All sensitive data lives exclusively within Encrypt ciphertext accounts.
//! Cross-chain asset custody is enforced by Ika's 2PC-MPC network — not by
//! any centralized authority or administrator key.

#![allow(unexpected_cfgs)]

// ─── Pinocchio Imports ────────────────────────────────────────────────────────
use pinocchio::{entrypoint, AccountView, Address, ProgramResult};
use pinocchio::error::ProgramError;

// ─── Encrypt SDK ─────────────────────────────────────────────────────────────
// use encrypt_pinocchio::EncryptContext;

// ─── Ika dWallet SDK ─────────────────────────────────────────────────────────
// use ika_dwallet_pinocchio::DWalletContext;

// ─── Internal modules ────────────────────────────────────────────────────────
pub mod state;
pub mod errors;
pub mod instructions;

// ─── Program ID (placeholder; replaced at deploy time) ───────────────────────
// Set to the keypair generated by `solana-keygen new -o target/deploy/private_rfq-keypair.json`
// Placeholder program ID — replaced by the actual keypair address at deploy time.
// Generate with: solana-keygen new -o target/deploy/private_rfq-keypair.json
// Then update Anchor.toml [programs.devnet] private_rfq = "<actual address>"
pub const ID: Address = Address::new_from_array([
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x01,
]);

// ─── Entrypoint ───────────────────────────────────────────────────────────────
entrypoint!(process_instruction);

/// Main instruction dispatcher.
///
/// The first byte of `data` is the instruction discriminator. All remaining
/// bytes are passed to the corresponding handler.
pub fn process_instruction(
    program_id: &Address,
    accounts:   &[AccountView],
    data:       &[u8],
) -> ProgramResult {
    let (discriminator, rest) = data
        .split_first()
        .ok_or(ProgramError::InvalidInstructionData)?;

    match *discriminator {
        // ── 0: Maker opens an encrypted RFQ ───────────────────────────────────
        0 => instructions::initialize_rfq::process(program_id, accounts, rest),

        // ── 1: Taker submits an encrypted bid + USDC escrow ───────────────────
        1 => instructions::submit_bid::process(program_id, accounts, rest),

        // ── 2: Request Encrypt to run the matching computation graph ──────────
        2 => instructions::request_fhe_match::process(program_id, accounts, rest),

        // ── 3: Request Encrypt to decrypt the match result ciphertext ─────────
        3 => instructions::request_match_decrypt::process(program_id, accounts, rest),

        // ── 4: Read the decrypted result; settle (true) or refund (false) ─────
        4 => instructions::reveal_match::process(program_id, accounts, rest),

        // ── 5: Maker calls Ika approve_message to authorize cross-chain TX ────
        5 => instructions::execute_settlement::process(program_id, accounts, rest),

        // ── 6: Emergency timeout after FHE computation stalls > 200 blocks ────
        6 => instructions::force_cancel_timeout::process(program_id, accounts, rest),

        _ => Err(ProgramError::InvalidInstructionData),
    }
}
